### ISSUE TITLE
Lack of a button plus other things

### ISSUE THREAD

**Issue by Felipefpl** [binoc-central/abprime#3]
Hi, 1st let me say i love the idea of ads being blocked before the site is even loaded like on Opera 50+, that's really great but there are problems to be solved.

1 - The lack of an options button like on other adblockers, idk how can i update the lists i want like this.

2 - The adblocker itself auto-downloading easylist (a problem that all adblockers have), this is bad because i dont like anyone choosing what i should have installed specially because i dont use easylist.

3 - The lists auto-update themselves and there is no way to stop it (another problem that all adblockers have), i want to update them manually when i wish to.

That's all, thank you for all your work on adblock latitude and in this one.

**Comment by mattatobin** [comment]
There really are no "Options" for ABPrime besides showing and hiding toolbar or statusbar icons.. Which are avaiable by clicking said buttons or from the ABPrime menu under Tools.

EasyList is the most likely filterlist people want so that is chosen at first run. I won't be changing that. Something has to be default. If it doesn't come with a configured default then new users will just claim it doesn't work and existing users who reinstall or install on a new profile or computer will complain that default behavior changed.

Auto update being able to be disabled has almost no use case because it is a constant battle between filterlists and websites.. Out of date filters will only cause issues for the majority.. However, patches welcome on this one if you think this is important.
